# Generated by Django 4.2.1 on 2023-08-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='last_name',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
