# Generated by Django 4.2.1 on 2023-08-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_home_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
