# Generated by Django 4.2.1 on 2023-08-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_socialnetwork_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='social_network',
        ),
        migrations.AddField(
            model_name='about',
            name='social_network',
            field=models.ManyToManyField(related_name='social_networks', to='app.socialnetwork'),
        ),
    ]
